<?php

namespace Planck\Extension\ViewComponent\View\Component;


use Planck\View\Component;


class Toolbar extends Component
{



    public function initialize()
    {
        parent::initialize();
        $this->setVariable('title', '');


    }


    public function setTitle($title)
    {
        $this->setVariable('title', $title);
    }

    public function render()
    {



        $this->dom->html(
            $this->obInclude(__DIR__.'/template.php', array_merge(
                    $this->getVariables(),
                    array(
                        //'saveArticleURL' => $saveArticleURL,
                    )
                )
            ));

        return parent::render(); // TODO: Change the autogenerated stub
    }


}
